use_frameworks!

platform :ios, '8.0'

target 'ComponentMediator_Example' do
  pod 'ComponentMediator', :path => '../'
  
  target 'ComponentMediator_Tests' do
    inherit! :search_paths

    
  end
end
